import { randomUUID } from "node:crypto";
import { pool, query } from "../db/pool.js";
import { seed } from "../db/seed.js";
import { evaluateAll } from "../services/evaluationService.js";
import { refreshFeatureStore } from "../features/refreshFeatureStore.js";
import { listUsers } from "../services/repository.js";
import { getRecommendations } from "../services/recommendationService.js";
import { writeModelArtifact } from "../services/modelArtifactService.js";

export async function batchScore() {
  await seed();
  await refreshFeatureStore();
  const version = `local-${new Date().toISOString().replace(/[:.]/g, "-")}`;
  const algorithmWeights = { popularity: 0.2, content: 0.4, collaborative: 0.4, semantic: 0 };
  const artifactPath = `artifacts/models/${version}.json`;
  await query(
    `INSERT INTO model_versions(id, version, status, approval_status, algorithm_weights, metrics, artifact_path)
     VALUES ($1, $2, 'training', 'pending', $3, '{}', $4)`,
    [randomUUID(), version, algorithmWeights, artifactPath]
  );
  const users = await listUsers();
  for (const user of users) await getRecommendations(user.id, "hybrid", 10);
  const evaluation = await evaluateAll(5);
  const writtenArtifactPath = await writeModelArtifact(version, artifactPath, {
    algorithmWeights,
    diversityLambda: 0.08,
    explorationRate: 0.08,
    metrics: evaluation,
    notes: [
      "Generated by local batch scoring.",
      "Canary live routing loads these weights when this version is assigned."
    ]
  });
  await query("UPDATE model_versions SET metrics = $1 WHERE version = $2", [evaluation, version]);
  return { version, status: "pending_approval", evaluation, artifactPath: writtenArtifactPath };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  batchScore().then((result) => console.log(JSON.stringify(result, null, 2))).finally(() => pool.end());
}
