ALTER TABLE users
  ADD COLUMN IF NOT EXISTS blocked_genres TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS boosted_providers TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS boosted_tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS personal_exploration NUMERIC(10,6) NOT NULL DEFAULT 0.08;
